### ISSUE TITLE
Finding resource in classpath

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/corenlp-small#1]
@kwalcock : I created this stripped-down version of CoreNLP so we can run the temporal expression recognizer wo/ the overall overhead of CoreNLP. However, the program fails to start due to its inability to find an existing resource in the classpath. Can you please take a look?

The class to run is: 
https://github.com/clulab/corenlp-small/blob/main/src/main/scala/edu/stanford/nlp/time/SUTimeAPI.scala

The code fails due to a null return at this line:
https://github.com/clulab/corenlp-small/blob/main/src/main/java/edu/stanford/nlp/time/JollyDayHolidays.java#L52

The resource it's looking for is here:
https://github.com/clulab/corenlp-small/blob/main/src/main/resources/edu/stanford/nlp/time/holidays/Holidays_sutime.xml

Thank you!
Mihai

**Comment by MihaiSurdeanu** [comment]
Btw, the file `Holidays_sutime.xml` exists under `src/main/java` as well in the original code, but I thought a better place for it is under `src/main/resources`.

**Comment by kwalcock** [comment]
The rules for looking up resources are confusing and not documented very well.  I'll check next chance.  Sometimes it helps to try both with and without the leading /.

**Comment by MihaiSurdeanu** [comment]
Thanks! I tried the leading /, and it didn't work...

**Comment by kwalcock** [comment]
It looks to me like it is expecting the file to be at edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml, so I accidentally moved it in main.  That's not the only problem, though.

**Comment by MihaiSurdeanu** [comment]
Not sure I understood this...

**Comment by kwalcock** [comment]
AFAICT, this line

https://github.com/clulab/corenlp-small/blob/2669c79bfee5d88eacf487da00add0d44af9a72f/src/main/java/edu/stanford/nlp/time/JollyDayHolidays.java#L39

says to move the file as such

https://github.com/clulab/corenlp-small/commit/2669c79bfee5d88eacf487da00add0d44af9a72f

**Comment by MihaiSurdeanu** [comment]
I see. I missed it. Thanks!
Can you please merge this. I will try to get it to work afterwards.

**Comment by kwalcock** [comment]
It was merged already by accident.
