### ISSUE TITLE
sbt publishLocal fails

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/corenlp-small#2]
Hi @kwalcock,

On this project, `sbt compile test` works fine, but `sbt publishLocal` fails with compilation errors... Can you please look into this? I wonder if I the build.sbt is incorrect in some way? It is pretty generic right now.

Thanks!

**Comment by kwalcock** [comment]
If you get people trying to build this with sbt on Windows, they will have problems because some of the Java source files include Unicode characters and Windows does not default to UTF8.  They might use

cmd> set _JAVA_OPTIONS=-Dfile.encoding=UTF-8

or

PS> $env:_JAVA_OPTIONS="-Dfile.encoding=UTF-8"

to make it work.  Other users who might have changed their defaults would also have problems.

**Comment by kwalcock** [comment]
`javacOptions ++= Seq("-encoding", "UTF-8")` took care of the problem above.  It will be in the PR.

**Comment by MihaiSurdeanu** [comment]
Thank you!


On February 5, 2021 at 10:43:01 AM, Keith Alcock (notifications@github.com)
wrote:

javacOptions ++= Seq("-encoding", "UTF-8") took care of the problem above.
It will be in the PR.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/corenlp-small/issues/2#issuecomment-774182138>,
or unsubscribe

**Comment by kwalcock** [comment]
See #3.  The local publish creates three jars: one for class files, another for source files, and a third for javadoc output.  The third one was failing.  It was trying to expose private inner classes and seemed to have problems with that.  Perhaps there are settings to get around it, but Stanford does not publish the javadoc version and it was easier to just disable it.  I'm not sure of the effect on a regular publish or release, but one will notice soon enough.

**Comment by MihaiSurdeanu** [comment]
Thanks!

Since CoreNLP publishes its own Java docs, I think it is safe to disable it.
